name: continuos-deployment
run-name: Deploy do App
on:
  pull-request:
      branches:
          - main
  workflow_dispatch:
  jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - uses: action/checkout@v4
            with:
              fetch-depth: 0

              - name: Docker Login
               uses: docker/login-action@v3.4.0
               with: 
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets. DOCKER_PASSWORD }}

              - name: Build and Push Docker image
                uses: docker/build-push-action@v6.15.0
                with: 
                  context: ./Dockerfile
                  push: true
                  tags: DevCarlosMoura/Aula-devops:latest
              
              - name: Azure WebApp
                uses: Azure/webapps-deploy@v3.0.1
                with:
                  app-name: DevCarlosMoura  
                  publish-profile: ${{ secrets.PUBLISH_PROFILE}}
                  image: DevCarlosMoura/Aula-devops
